const contentArea=document.getElementById('contentArea');
const pageTitle=document.getElementById('pageTitle');
const mobileMenuBtn=document.getElementById('mobileMenuBtn');
const sidebar=document.getElementById('sidebar');
const sideNav=document.getElementById('sideNav');

const moduleRegistry=[
 {id:'dashboard',label:'Dashboard',desc:'Business overview, KPIs, quick actions and module launch center.'},
 {id:'crm',label:'Customer CRM',desc:'Customer records, leads, follow-ups, contacts, timelines and financial summary.'},
 {id:'commerce',label:'Commerce Core',desc:'Quotations, delivery orders, invoices, payments, receipts, expenses and P&L.'},
 {id:'projects',label:'Project Management',desc:'Projects, tasks, milestones, team assignment, project files and profitability.'},
 {id:'website',label:'Website Builder',desc:'Website requirements, pages, domain, hosting, deployment, SEO and maintenance.'},
 {id:'support',label:'Support Center',desc:'Tickets, SLA monitoring, assignments, support updates and knowledge base.'},
 {id:'assets',label:'Asset Management',desc:'Internal and customer assets, assignment, maintenance and warranty tracking.'},
 {id:'vendors',label:'Vendor Management',desc:'Vendors, purchases, contacts, contracts, price lists and vendor expenses.'},
 {id:'employees',label:'Employee Management',desc:'Employee profiles, attendance, leave, claims, tasks and performance.'},
 {id:'documents',label:'Document Repository',desc:'Central document storage for customers, projects, finance, HR and vendors.'},
 {id:'reports',label:'Reports & Analytics',desc:'CRM, sales, financial, project, support and operational reports.'},
 {id:'audit',label:'Audit Logs',desc:'Activity tracking for created, updated, deleted and workflow actions.'},
 {id:'settings',label:'Settings',desc:'Company profile, numbering, tax, currency, roles and system preferences.'}
];

function money(v){return 'RM '+(Number(v)||0).toFixed(2)}
function seedNav(){sideNav.innerHTML=moduleRegistry.map((m,i)=>`<button class="nav-link ${i===0?'active':''}" data-page="${m.id}">${m.label}</button>`).join('');document.querySelectorAll('.nav-link').forEach(btn=>btn.addEventListener('click',()=>loadPage(btn.dataset.page)));}
function setActive(p){document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===p));}
function loadPage(p){const page=pages[p]||pages.dashboard;pageTitle.textContent=page.title;setActive(p);page.render();sidebar.classList.remove('open');}
function moduleCards(filterIds){const list=filterIds?moduleRegistry.filter(m=>filterIds.includes(m.id)):moduleRegistry;return `<div class="module-list">${list.map(m=>`<div class="module-card" onclick="loadPage('${m.id}')"><h3>${m.label}</h3><span class="status blue">Open Module</span><p class="muted">${m.desc}</p></div>`).join('')}</div>`;}
function pageHeader(title,desc,action=''){return `<div class="page-header"><div><h2>${title}</h2><p>${desc}</p></div>${action}</div>`;}

const pages={
 dashboard:{title:'Dashboard',render:renderDashboard},crm:{title:'Customer CRM',render:renderCRM},commerce:{title:'Commerce Core',render:renderCommerce},projects:{title:'Project Management',render:renderProjects},website:{title:'Website Builder',render:renderWebsiteBuilder},support:{title:'Support Center',render:renderSupport},assets:{title:'Asset Management',render:renderAssets},vendors:{title:'Vendor Management',render:renderVendors},employees:{title:'Employee Management',render:renderEmployees},documents:{title:'Document Repository',render:renderDocuments},reports:{title:'Reports & Analytics',render:renderReports},audit:{title:'Audit Logs',render:renderAudit},settings:{title:'Settings',render:renderSettings}
};

function renderDashboard(){const customers=DB.get('customers'),projects=DB.get('projects'),tickets=DB.get('tickets'),assets=DB.get('assets'),vendors=DB.get('vendors'),employees=DB.get('employees'),documents=DB.get('documents'),invoices=DB.get('invoices'),expenses=DB.get('expenses');const revenue=invoices.reduce((s,i)=>s+(Number(i.total)||0),0);const exp=expenses.reduce((s,e)=>s+(Number(e.amount)||0),0);contentArea.innerHTML=`${pageHeader('Welcome Mohan','ClientPro Hub v1.6 complete module routing dashboard. Every sidebar item and dashboard module card is clickable.',`<button class="primary-btn" onclick="loadPage('projects')">+ New Project</button>`)}<div class="grid"><div class="card"><span class="muted">Customers</span><div class="metric">${customers.length}</div></div><div class="card"><span class="muted">Projects</span><div class="metric">${projects.length}</div></div><div class="card"><span class="muted">Open Tickets</span><div class="metric">${tickets.filter(t=>t.status!=='Closed').length}</div></div><div class="card"><span class="muted">Net Profit</span><div class="metric">${money(revenue-exp)}</div></div></div><div class="grid-3" style="margin-top:16px"><div class="card"><h3>Business Records</h3><p>Assets: <b>${assets.length}</b></p><p>Vendors: <b>${vendors.length}</b></p><p>Employees: <b>${employees.length}</b></p><p>Documents: <b>${documents.length}</b></p></div><div class="card"><h3>Quick Actions</h3><div class="action-row"><button class="secondary-btn" onclick="loadPage('crm')">Add Customer</button><button class="secondary-btn" onclick="loadPage('commerce')">Commerce</button><button class="secondary-btn" onclick="loadPage('support')">Ticket</button><button class="secondary-btn" onclick="loadPage('website')">Website</button></div></div><div class="card"><h3>System Status</h3><span class="status green">Routing Active</span><span class="status green" style="margin-left:8px">LocalStorage Active</span><p class="muted" style="margin-top:10px">All modules from Dashboard to Settings are now clickable.</p></div></div><h3 style="margin-top:22px">All Modules</h3>${moduleCards()}`;}

function renderCRM(){const customers=DB.get('customers');contentArea.innerHTML=`${pageHeader('Customer CRM','Manage leads, customers, contacts, follow-ups, timelines, documents and financial summaries.')}<div class="card"><h3>Add Customer</h3><div class="form-row"><input class="input" id="customerName" placeholder="Customer / Company Name"><input class="input" id="customerPhone" placeholder="Phone / WhatsApp"></div><div class="form-row"><input class="input" id="customerEmail" placeholder="Email"><select class="select" id="customerStatus"><option>Lead</option><option>Prospect</option><option>Active</option><option>Inactive</option><option>VIP</option></select></div><div class="action-row"><button class="primary-btn" onclick="addCustomer()">Save Customer</button></div></div><div class="card"><h3>Customer List</h3><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Status</th></tr></thead><tbody>${customers.map(c=>`<tr><td>${c.name||'-'}</td><td>${c.phone||'-'}</td><td>${c.email||'-'}</td><td><span class="status green">${c.status||'Lead'}</span></td></tr>`).join('')||'<tr><td colspan="4">No customers added yet.</td></tr>'}</tbody></table></div>${subCards(['Leads','Contacts','Follow-Ups','Timeline','Customer Documents','Financial Summary'])}`;}
function addCustomer(){const name=document.getElementById('customerName').value.trim();if(!name){alert('Please enter customer name.');return;}DB.add('customers',{name,phone:document.getElementById('customerPhone').value,email:document.getElementById('customerEmail').value,status:document.getElementById('customerStatus').value});DB.add('auditLogs',{module:'CRM',action:'Customer created',record:name});renderCRM();}

function renderCommerce(){contentArea.innerHTML=`${pageHeader('Commerce Core','Quotation → Delivery Order → Invoice → Payment → Official Receipt → P&L.')}${subCards(['Quotations','Delivery Orders','Invoices','Payments','Official Receipts','Customer Statements','Expenses','Tax & Discount','Profit & Loss'])}<div class="card" style="margin-top:16px"><h3>PDF Preview Center</h3><div class="pdf-preview">Quotation / DO / Invoice / Receipt PDF preview area</div><div class="action-row"><button class="secondary-btn" onclick="alert('PDF preview workflow placeholder')">Preview</button><button class="secondary-btn">Print</button><button class="secondary-btn">Download</button><button class="secondary-btn">WhatsApp</button></div></div>`;}

function renderProjects(){const projects=DB.get('projects'),tasks=DB.get('tasks'),milestones=DB.get('milestones');contentArea.innerHTML=`${pageHeader('Project Management','Create projects, track tasks, milestones, expenses, team assignment and profitability.')}<div class="card"><h3>Create Project</h3><div class="form-row-3"><input class="input" id="projectName" placeholder="Project Name"><select class="select" id="projectType"><option>Website</option><option>App</option><option>CCTV</option><option>Networking</option><option>Consultancy</option></select><select class="select" id="projectStatus"><option>Planning</option><option>Active</option><option>Testing</option><option>Completed</option></select></div><div class="form-row-3"><input class="input" id="projectCustomer" placeholder="Customer Name"><input class="input" id="projectBudget" type="number" placeholder="Budget RM"><input class="input" id="projectCost" type="number" placeholder="Estimated Cost RM"></div><div class="action-row"><button class="primary-btn" onclick="addProject()">Save Project</button><button class="secondary-btn" onclick="seedProjectDemo()">Add Demo Project</button></div></div><div class="grid"><div class="card"><span class="muted">Total Projects</span><div class="metric">${projects.length}</div></div><div class="card"><span class="muted">Tasks</span><div class="metric">${tasks.length}</div></div><div class="card"><span class="muted">Milestones</span><div class="metric">${milestones.length}</div></div><div class="card"><span class="muted">Active</span><div class="metric">${projects.filter(p=>p.status==='Active').length}</div></div></div><div class="card" style="margin-top:16px"><h3>Project List</h3><table class="table"><thead><tr><th>Project</th><th>Customer</th><th>Type</th><th>Status</th><th>Budget</th><th>Profit</th></tr></thead><tbody>${projects.map(p=>`<tr><td>${p.name}</td><td>${p.customer||'-'}</td><td>${p.type}</td><td><span class="status green">${p.status}</span></td><td>${money(p.budget)}</td><td>${money((Number(p.budget)||0)-(Number(p.cost)||0))}</td></tr>`).join('')||'<tr><td colspan="6">No projects yet.</td></tr>'}</tbody></table></div>${subCards(['Tasks','Milestones','Team Assignment','Project Expenses','Project Profitability','Project Files'])}`;}
function addProject(){const name=document.getElementById('projectName').value.trim();if(!name){alert('Please enter project name.');return;}DB.add('projects',{name,type:document.getElementById('projectType').value,status:document.getElementById('projectStatus').value,customer:document.getElementById('projectCustomer').value,budget:document.getElementById('projectBudget').value,cost:document.getElementById('projectCost').value});DB.add('auditLogs',{module:'Projects',action:'Project created',record:name});renderProjects();}
function seedProjectDemo(){DB.add('projects',{name:'ABC Corporate Website',type:'Website',status:'Active',customer:'ABC Sdn Bhd',budget:5000,cost:1280});DB.add('tasks',{name:'Collect website content',project:'ABC Corporate Website',status:'In Progress'});DB.add('milestones',{name:'Design Approval',project:'ABC Corporate Website',status:'Pending'});renderProjects();}

function renderWebsiteBuilder(){const sites=DB.get('websiteProjects'),domains=DB.get('domains'),deploy=DB.get('deployments');contentArea.innerHTML=`${pageHeader('Website Builder','Manage requirements, pages, domain, hosting, deployment, SEO and maintenance.')}<div class="card"><h3>Create Website Project</h3><div class="form-row-3"><input class="input" id="siteName" placeholder="Website Project Name"><select class="select" id="siteType"><option>Corporate Website</option><option>Landing Page</option><option>E-Commerce</option><option>Portfolio</option><option>Blog</option></select><select class="select" id="siteTech"><option>HTML/CSS/JS</option><option>WordPress</option><option>React</option><option>NextJS</option></select></div><div class="form-row-3"><input class="input" id="siteDomain" placeholder="Domain e.g. example.com"><input class="input" id="siteNetlify" placeholder="Netlify URL"><input class="input" id="siteGithub" placeholder="GitHub Repository"></div><div class="action-row"><button class="primary-btn" onclick="addWebsiteProject()">Save Website Project</button></div></div><div class="grid"><div class="card"><span class="muted">Website Projects</span><div class="metric">${sites.length}</div></div><div class="card"><span class="muted">Domains</span><div class="metric">${domains.length}</div></div><div class="card"><span class="muted">Deployments</span><div class="metric">${deploy.length}</div></div><div class="card"><span class="muted">Maintenance</span><div class="metric">0</div></div></div><div class="card" style="margin-top:16px"><h3>Website Project List</h3><table class="table"><thead><tr><th>Project</th><th>Type</th><th>Technology</th><th>Domain</th><th>Netlify</th></tr></thead><tbody>${sites.map(s=>`<tr><td>${s.name}</td><td>${s.type}</td><td>${s.tech}</td><td>${s.domain||'-'}</td><td>${s.netlify||'-'}</td></tr>`).join('')||'<tr><td colspan="5">No website projects yet.</td></tr>'}</tbody></table></div>${subCards(['Requirements','Sitemap','Pages','Design','Content','Domain','Hosting','Deployment','SEO','Maintenance'])}`;}
function addWebsiteProject(){const name=document.getElementById('siteName').value.trim();if(!name){alert('Please enter website project name.');return;}DB.add('websiteProjects',{name,type:document.getElementById('siteType').value,tech:document.getElementById('siteTech').value,domain:document.getElementById('siteDomain').value,netlify:document.getElementById('siteNetlify').value,github:document.getElementById('siteGithub').value});if(document.getElementById('siteDomain').value)DB.add('domains',{domain:document.getElementById('siteDomain').value,status:'Active'});if(document.getElementById('siteNetlify').value)DB.add('deployments',{name,netlify:document.getElementById('siteNetlify').value,status:'Live'});DB.add('auditLogs',{module:'Website Builder',action:'Website project created',record:name});renderWebsiteBuilder();}

function renderSupport(){const tickets=DB.get('tickets');contentArea.innerHTML=`${pageHeader('Support Center','Create and manage support tickets with priority, assignment and status tracking.')}<div class="card"><h3>Create Ticket</h3><div class="form-row-3"><input class="input" id="ticketSubject" placeholder="Ticket Subject"><select class="select" id="ticketCategory"><option>Hardware</option><option>Software</option><option>Network</option><option>Website</option><option>Application</option><option>CCTV</option></select><select class="select" id="ticketPriority"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><textarea class="textarea" id="ticketDesc" placeholder="Issue description" style="margin-top:12px"></textarea><div class="action-row"><button class="primary-btn" onclick="addTicket()">Save Ticket</button></div></div><div class="grid"><div class="card"><span class="muted">Open</span><div class="metric">${tickets.filter(t=>t.status==='Open').length}</div></div><div class="card"><span class="muted">In Progress</span><div class="metric">${tickets.filter(t=>t.status==='In Progress').length}</div></div><div class="card"><span class="muted">Resolved</span><div class="metric">${tickets.filter(t=>t.status==='Resolved').length}</div></div><div class="card"><span class="muted">Closed</span><div class="metric">${tickets.filter(t=>t.status==='Closed').length}</div></div></div><div class="card" style="margin-top:16px"><h3>Ticket List</h3><table class="table"><thead><tr><th>Subject</th><th>Category</th><th>Priority</th><th>Status</th></tr></thead><tbody>${tickets.map(t=>`<tr><td>${t.subject}</td><td>${t.category}</td><td>${t.priority}</td><td><span class="status orange">${t.status}</span></td></tr>`).join('')||'<tr><td colspan="4">No tickets yet.</td></tr>'}</tbody></table></div>${subCards(['SLA Monitoring','Knowledge Base','Assigned Tickets','Support Reports'])}`;}
function addTicket(){const subject=document.getElementById('ticketSubject').value.trim();if(!subject){alert('Please enter ticket subject.');return;}DB.add('tickets',{subject,category:document.getElementById('ticketCategory').value,priority:document.getElementById('ticketPriority').value,description:document.getElementById('ticketDesc').value,status:'Open'});DB.add('auditLogs',{module:'Support',action:'Ticket created',record:subject});renderSupport();}

function renderAssets(){const assets=DB.get('assets');contentArea.innerHTML=`${pageHeader('Asset Management','Track company and customer assets, serial numbers, warranty, assignments and maintenance.')}<div class="card"><h3>Add Asset</h3><div class="form-row-3"><input class="input" id="assetName" placeholder="Asset Name"><input class="input" id="assetSerial" placeholder="Serial Number"><select class="select" id="assetType"><option>Laptop</option><option>Printer</option><option>Router</option><option>CCTV Camera</option><option>NVR</option><option>Switch</option></select></div><div class="action-row"><button class="primary-btn" onclick="addAsset()">Save Asset</button></div></div>${recordTable('Asset List',assets,['name','serial','type','status'])}${subCards(['Assignments','Maintenance','Warranty Tracking','Asset Reports'])}`;}
function addAsset(){const name=document.getElementById('assetName').value.trim();if(!name){alert('Please enter asset name.');return;}DB.add('assets',{name,serial:document.getElementById('assetSerial').value,type:document.getElementById('assetType').value,status:'Available'});renderAssets();}

function renderVendors(){const vendors=DB.get('vendors');contentArea.innerHTML=`${pageHeader('Vendor Management','Manage vendors, contacts, contracts, price lists, purchase history and expenses.')}<div class="card"><h3>Add Vendor</h3><div class="form-row-3"><input class="input" id="vendorName" placeholder="Vendor Company"><input class="input" id="vendorContact" placeholder="Contact Person"><input class="input" id="vendorPhone" placeholder="Phone"></div><div class="action-row"><button class="primary-btn" onclick="addVendor()">Save Vendor</button></div></div>${recordTable('Vendor List',vendors,['company','contact','phone','rating'])}${subCards(['Purchases','Contracts','Price Lists','Vendor Reports'])}`;}
function addVendor(){const company=document.getElementById('vendorName').value.trim();if(!company){alert('Please enter vendor company.');return;}DB.add('vendors',{company,contact:document.getElementById('vendorContact').value,phone:document.getElementById('vendorPhone').value,rating:'New'});renderVendors();}

function renderEmployees(){const employees=DB.get('employees');contentArea.innerHTML=`${pageHeader('Employee Management','Manage employees, attendance, leave, claims, project assignments and performance.')}<div class="card"><h3>Add Employee</h3><div class="form-row-3"><input class="input" id="empName" placeholder="Employee Name"><input class="input" id="empRole" placeholder="Designation"><select class="select" id="empStatus"><option>Active</option><option>Inactive</option><option>On Leave</option></select></div><div class="action-row"><button class="primary-btn" onclick="addEmployee()">Save Employee</button></div></div>${recordTable('Employee List',employees,['name','role','status','department'])}${subCards(['Attendance','Leave','Claims','Tasks','Performance'])}`;}
function addEmployee(){const name=document.getElementById('empName').value.trim();if(!name){alert('Please enter employee name.');return;}DB.add('employees',{name,role:document.getElementById('empRole').value,status:document.getElementById('empStatus').value,department:'Operations'});renderEmployees();}

function renderDocuments(){const docs=DB.get('documents');contentArea.innerHTML=`${pageHeader('Document Repository','Store customer, project, finance, HR, vendor and contract documents.')}<div class="card"><h3>Add Document Record</h3><div class="form-row-3"><input class="input" id="docName" placeholder="Document Name"><select class="select" id="docType"><option>Customer</option><option>Project</option><option>Finance</option><option>HR</option><option>Vendor</option><option>Contract</option></select><input class="input" id="docRef" placeholder="Reference / Related Record"></div><div class="action-row"><button class="primary-btn" onclick="addDocument()">Save Document Record</button></div></div>${recordTable('Document List',docs,['name','type','reference','version'])}${subCards(['Customer Files','Project Files','Financial Documents','HR Documents','Vendor Documents','Contracts'])}`;}
function addDocument(){const name=document.getElementById('docName').value.trim();if(!name){alert('Please enter document name.');return;}DB.add('documents',{name,type:document.getElementById('docType').value,reference:document.getElementById('docRef').value,version:'v1.0'});renderDocuments();}

function renderReports(){contentArea.innerHTML=`${pageHeader('Reports & Analytics','View CRM, finance, project, support, asset and operational reports.')}<div class="grid"><div class="card"><span class="muted">CRM Reports</span><div class="metric">${DB.get('customers').length}</div></div><div class="card"><span class="muted">Project Reports</span><div class="metric">${DB.get('projects').length}</div></div><div class="card"><span class="muted">Support Reports</span><div class="metric">${DB.get('tickets').length}</div></div><div class="card"><span class="muted">Asset Reports</span><div class="metric">${DB.get('assets').length}</div></div></div>${subCards(['Profit & Loss','Cash Flow','Customer Value','Project Profitability','Ticket SLA','Asset Summary'])}<div class="card" style="margin-top:16px"><h3>Export Center</h3><div class="action-row"><button class="secondary-btn">Export PDF</button><button class="secondary-btn">Export Excel</button><button class="secondary-btn">Print</button></div></div>`;}
function renderAudit(){const logs=DB.get('auditLogs');contentArea.innerHTML=`${pageHeader('Audit Logs','Track system activity, data changes and workflow actions.')}<div class="card"><h3>Activity Logs</h3><table class="table"><thead><tr><th>Date</th><th>Module</th><th>Action</th><th>Record</th></tr></thead><tbody>${logs.slice().reverse().map(l=>`<tr><td>${new Date(l.createdAt).toLocaleString()}</td><td>${l.module}</td><td>${l.action}</td><td>${l.record||'-'}</td></tr>`).join('')||'<tr><td colspan="4">No audit logs yet.</td></tr>'}</tbody></table></div>`;}
function renderSettings(){contentArea.innerHTML=`${pageHeader('Settings','Configure company profile, commerce numbering, tax, currency, users and permissions.')}<div class="grid-2"><div class="card"><h3>Company Profile</h3><div class="form-row"><input class="input" value="K&M TechSpire Solution" placeholder="Company Name"><input class="input" value="NS0313320-D" placeholder="SSM Number"></div><div class="form-row"><input class="input" value="mohan@knmtechspiresolution.com" placeholder="Email"><input class="input" value="RM" placeholder="Currency"></div><div class="action-row"><button class="primary-btn">Save Settings</button></div></div><div class="card"><h3>System Tools</h3><p class="muted">Use carefully during testing.</p><div class="action-row"><button class="secondary-btn" onclick="loadPage('audit')">View Audit Logs</button><button class="danger-btn" onclick="if(confirm('Clear local app data?')){DB.clearAll();loadPage('dashboard')}">Clear Local Data</button></div></div></div>${subCards(['Quotation Prefix','Invoice Prefix','Receipt Prefix','Tax Settings','Discount Rules','User Roles','Permissions'])}`;}

function subCards(items){return `<div class="module-list">${items.map(i=>`<div class="module-card" onclick="alert('${i} screen placeholder ready for next functional sprint')"><h3>${i}</h3><span class="status green">Routed</span><p class="muted">Click action is active. Detailed function comes in the next sprint.</p></div>`).join('')}</div>`;}
function recordTable(title,rows,cols){return `<div class="card" style="margin-top:16px"><h3>${title}</h3><table class="table"><thead><tr>${cols.map(c=>`<th>${c.charAt(0).toUpperCase()+c.slice(1)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${r[c]||'-'}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">No records yet.</td></tr>`}</tbody></table></div>`;}

seedNav();mobileMenuBtn.addEventListener('click',()=>sidebar.classList.toggle('open'));document.getElementById('quickCreateBtn').addEventListener('click',()=>loadPage('crm'));loadPage('dashboard');
