(function(){
var app=document.getElementById('app'), title=document.getElementById('pageTitle'), nav=document.getElementById('nav');
var menuBtn=document.getElementById('menuBtn'); if(menuBtn){menuBtn.addEventListener('click',function(){document.getElementById('sidebar').classList.toggle('open');});}
var modules=[['dashboard','Dashboard'],['crm','Customer CRM'],['projects','Project Management'],['commerce','Commerce Core'],['website','Website Builder'],['support','Support Center'],['assets','Asset Management'],['vendors','Vendor Management'],['employees','Employee Management'],['documents','Document Repository'],['reports','Reports & Analytics'],['audit','Audit Logs'],['settings','Settings']];
var moduleSubs={dashboard:['KPIs','Quick Actions','Recent Activities','Module Launcher'],crm:['Customers','Leads','Prospects','Customer Profiles','Contact History','Financial Summary','Customer Statement'],projects:['Project Creation','Customer Linked Projects','Budget Tracking','Cost Tracking','Profitability','Tasks','Milestones','Files'],commerce:['Quotations Flow','Create Quotation','Delivery Orders','Invoices','Payments','Official Receipts','Customer Statements','Document Templates'],website:['Website Projects','Domains','Hosting','Deployment','SEO','Maintenance'],support:['Tickets','Customer Support','Project Support','Resolution Tracking','SLA Monitoring'],assets:['Assets','Serial Numbers','Assignment','Maintenance','Warranty'],vendors:['Vendors','Procurement','Rating','Purchase Tracking','Contracts'],employees:['Employees','Roles','Departments','Assignments','Performance'],documents:['Customer Documents','Project Documents','Finance Documents','Internal Documents','Templates'],reports:['Revenue','Outstanding','Customer Value','Cash Flow','Profit & Loss','Project Profitability'],audit:['CRM Logs','Project Logs','Commerce Logs','Settings Logs','System Logs'],settings:['Company Profile','Logo','SSM Number','Bank Details','Terms & Conditions','Tax Settings','Document Prefixes','Backup Export','Restore Data']};
var commerceTabs=[['overview','Flow Overview'],['create-quotation','Create Quotation'],['quotations','Quotations'],['delivery-orders','Delivery Orders'],['invoices','Invoices'],['payments','Payments'],['receipts','Official Receipts'],['statements','Statements'],['templates','Templates']];
var quoteDraft=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function money(v){return 'RM '+(Number(v)||0).toFixed(2);}function stamp(k,p){return p+'-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+String(DB.get(k).length+1).padStart(3,'0');}
function customerName(id){var x=DB.get('customers').find(function(c){return c.id===id;});return x?x.name:'Unlinked / Manual';}function projectName(id){var x=DB.get('projects').find(function(p){return p.id===id;});return x?x.name:'-';}
function customerOptions(){return '<option value="">-- Select Customer --</option>'+DB.get('customers').map(function(c){return '<option value="'+c.id+'">'+esc(c.name)+'</option>';}).join('');}function projectOptions(){return '<option value="">-- Select Project --</option>'+DB.get('projects').map(function(p){return '<option value="'+p.id+'">'+esc(p.name)+' - '+esc(customerName(p.customerId))+'</option>';}).join('');}
function pageHead(t,d,a){title.textContent=t;return '<div class="page-head"><div><h2>'+esc(t)+'</h2><p class="muted">'+esc(d)+'</p></div>'+(a||'')+'</div>';}function table(t,rows,cols){return '<div class="card" style="margin-top:16px"><h3>'+esc(t)+'</h3><table><thead><tr>'+cols.map(function(c){return '<th>'+esc(c)+'</th>';}).join('')+'</tr></thead><tbody>'+(rows||'<tr><td colspan="'+cols.length+'">No records yet.</td></tr>')+'</tbody></table></div>';}
function route(key,opts){document.querySelectorAll('#nav button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-route')===key);});(pages[key]||pages.generic)(opts||{});document.getElementById('sidebar').classList.remove('open');}window.go=function(key){route(key);};
function renderNav(){nav.innerHTML=modules.map(function(m,i){return '<button type="button" class="'+(i===0?'active':'')+'" data-route="'+m[0]+'">'+m[1]+'</button>';}).join('');}
document.addEventListener('click',function(e){var r=e.target.getAttribute&&e.target.getAttribute('data-route');if(r){route(r,{tab:e.target.getAttribute('data-commerce-tab')});}var tab=e.target.getAttribute&&e.target.getAttribute('data-commerce-tab');if(tab && !r){renderCommerce(tab);}var sub=e.target.getAttribute&&e.target.getAttribute('data-sub');if(sub){openSub(e.target.getAttribute('data-module'),sub);}});
function subnav(key){return '<div class="subnav">'+(moduleSubs[key]||[]).map(function(s){return '<button type="button" data-sub="'+esc(s)+'" data-module="'+esc(key)+'">'+esc(s)+'</button>';}).join('')+'</div>';}
function openSub(mod,sub){if(mod==='commerce'){var map={'Quotations Flow':'overview','Create Quotation':'create-quotation','Delivery Orders':'delivery-orders','Invoices':'invoices','Payments':'payments','Official Receipts':'receipts','Customer Statements':'statements','Document Templates':'templates'};route('commerce',{tab:map[sub]||'overview'});return;}app.innerHTML=pageHead(sub,(modules.find(function(m){return m[0]===mod;})||['',mod])[1]+' submodule is accessible.','<button class="secondary" data-route="'+mod+'">Back</button>')+'<div class="card"><h3>'+esc(sub)+'</h3><p class="muted">This submodule is accessible and ready for detailed form expansion.</p><span class="status green">Accessible</span></div>';}
var pages={};
pages.dashboard=function(){var c=DB.get('customers'),p=DB.get('projects'),q=DB.get('quotations'),i=DB.get('invoices');app.innerHTML=pageHead('Dashboard','Commerce flow is unified inside Commerce Core.')+subnav('dashboard')+'<div class="grid"><div class="card"><span class="muted">Customers</span><div class="metric">'+c.length+'</div></div><div class="card"><span class="muted">Projects</span><div class="metric">'+p.length+'</div></div><div class="card"><span class="muted">Quotations</span><div class="metric">'+q.length+'</div></div><div class="card"><span class="muted">Invoices</span><div class="metric">'+i.length+'</div></div></div><div class="cards">'+modules.filter(function(m){return m[0]!=='dashboard';}).map(function(m){return '<div class="module" data-route="'+m[0]+'"><h3>'+m[1]+'</h3><span class="status green">Accessible</span><p class="muted">Open '+m[1]+'.</p></div>';}).join('')+'</div>';};
pages.crm=function(){var rows=DB.get('customers').map(function(c){return '<tr><td>'+esc(c.name)+'</td><td>'+esc(c.phone||'-')+'</td><td>'+esc(c.email||'-')+'</td></tr>';}).join('');app.innerHTML=pageHead('Customer CRM','Create and manage customer records.')+subnav('crm')+'<div class="card"><h3>Add Customer</h3><div class="row"><input id="cName" placeholder="Customer / Company"><input id="cPhone" placeholder="Phone"></div><div class="row"><input id="cEmail" placeholder="Email"><input id="cAddress" placeholder="Address"></div><div class="actions"><button class="primary" id="saveCustomer">Save Customer</button></div></div>'+table('Customers',rows,['Name','Phone','Email']);document.getElementById('saveCustomer').onclick=function(){var n=document.getElementById('cName').value.trim();if(!n){alert('Enter customer name');return;}DB.add('customers',{name:n,phone:cPhone.value,email:cEmail.value,address:cAddress.value});route('crm');};};
pages.projects=function(){var rows=DB.get('projects').map(function(p){return '<tr><td>'+esc(p.name)+'</td><td>'+esc(customerName(p.customerId))+'</td><td>'+esc(p.type)+'</td></tr>';}).join('');app.innerHTML=pageHead('Project Management','Create projects linked to customers.')+subnav('projects')+'<div class="card"><h3>Create Project</h3><div class="row3"><input id="pName" placeholder="Project Name"><select id="pCustomer">'+customerOptions()+'</select><select id="pType"><option>Website</option><option>App</option><option>CCTV</option><option>Networking</option><option>Consultancy</option></select></div><div class="actions"><button class="primary" id="saveProject">Save Project</button></div></div>'+table('Projects',rows,['Project','Customer','Type']);document.getElementById('saveProject').onclick=function(){if(!pName.value.trim()||!pCustomer.value){alert('Enter project and customer');return;}DB.add('projects',{name:pName.value,customerId:pCustomer.value,type:pType.value,status:'Active'});route('projects');};};
pages.commerce=function(opts){renderCommerce((opts&&opts.tab)||'overview');};
function commerceLayout(active,body){var tabs='<div class="commerce-tabs">'+commerceTabs.map(function(t){return '<button type="button" class="'+(active===t[0]?'active':'')+'" data-commerce-tab="'+t[0]+'">'+t[1]+'</button>';}).join('')+'</div>';app.innerHTML=pageHead('Commerce Core','Quotation → Delivery Order → Invoice → Payment → Official Receipt flow in one module.')+tabs+body;}
function flowLine(current){var steps=['Create Quotation','Quotations','Delivery Orders','Invoices','Payments','Official Receipts'];return '<div class="flow-line">'+steps.map(function(s,i){var cls=(s===current?'current':(steps.indexOf(current)>i?'done':''));return '<span class="flow-step '+cls+'">'+(i+1)+'. '+s+'</span>';}).join('')+'</div>';}
function renderCommerce(tab){if(tab==='create-quotation')return commerceCreateQuote();if(tab==='quotations')return commerceQuotationList();if(tab==='delivery-orders')return commerceDeliveryOrders();if(tab==='invoices')return commerceInvoices();if(tab==='payments')return commercePayments();if(tab==='receipts')return commerceReceipts();if(tab==='statements')return commerceStatements();if(tab==='templates')return commerceTemplates();commerceLayout('overview',flowLine('Create Quotation')+'<div class="grid"><div class="card"><span class="muted">Quotations</span><div class="metric">'+DB.get('quotations').length+'</div></div><div class="card"><span class="muted">Delivery Orders</span><div class="metric">'+DB.get('deliveryOrders').length+'</div></div><div class="card"><span class="muted">Invoices</span><div class="metric">'+DB.get('invoices').length+'</div></div><div class="card"><span class="muted">Official Receipts</span><div class="metric">'+DB.get('receipts').length+'</div></div></div><div class="note"><b>Commerce Flow:</b> Create Quotation → approve/create Delivery Order → create Invoice → record Payment → generate Official Receipt.</div><div class="cards">'+commerceTabs.filter(function(t){return t[0]!=='overview';}).map(function(t){return '<div class="module" data-commerce-tab="'+t[0]+'"><h3>'+t[1]+'</h3><span class="status green">Flow</span><p class="muted">Open inside Commerce Core.</p></div>';}).join('')+'</div>');}
function commerceCreateQuote(){commerceLayout('create-quotation',flowLine('Create Quotation')+
'<div class="grid2"><div class="card"><h3>Quotation Header</h3>'+ 
'<div class="row"><select id="qCustomer">'+customerOptions()+'</select><select id="qProject">'+projectOptions()+'</select></div>'+ 
'<div class="row3"><input id="qFor" placeholder="Quotation For / Customer Title"><select id="qCustomerType"><option>Corporate</option><option>Individual</option><option>Government</option><option>SME</option></select><input id="qPaymentTerms" value="Online Banking" placeholder="Payment Terms"></div>'+ 
'<div class="row3"><input id="qSalesperson" value="Mohan Samugom" placeholder="Salesperson"><input id="qPoNumber" value="N/A" placeholder="P.O. Number"><input id="qShipDate" placeholder="Ship Date"></div>'+ 
'<div class="row3"><input id="qShipVia" placeholder="Ship Via"><input id="qValid" type="date"><select id="qStatus"><option>Draft</option><option>Sent</option><option>Approved</option></select></div>'+ 
'<input id="qRemark" placeholder="Remark" style="margin-top:12px"></div>'+ 
'<div class="card"><h3>Terms & Conditions</h3><p class="muted">Manual editable area with sufficient space. This will print in the document.</p><textarea id="qTerms" class="terms-editor">Price Validity: 7 days validity only & subject to change WITHOUT prior notice.\nDelivery Lead Time: B2B Order Subject to parts availability.\nPayment Term: Online Banking.\nPayment Overdue: 1.5% on overdue payment once PO is issued.\nCancellation: No Cancellation After PO.\nThis quotation adhered to K&M TechSpire Solution sales, products and general terms & conditions abided by customer without any dispute.\nWe trust the above in order and looking forward to close deal with you.</textarea></div></div>'+ 
'<div class="grid2" style="margin-top:16px"><div class="card"><h3>Add Item / Description</h3><div class="row"><input id="lineModel" placeholder="Model / Product Code"><input id="lineDesc" placeholder="Description"></div><div class="row3"><input id="lineQty" type="number" value="1" placeholder="Qty"><input id="linePrice" type="number" placeholder="Unit Price RM"><input id="lineDiscount" type="number" value="0" placeholder="Discount RM"></div><div class="row"><input id="lineTax" type="number" value="0" placeholder="Tax %"><button class="primary" id="addLine">+ Add Item</button></div></div>'+ 
'<div class="card"><h3>Reference Format</h3><p class="muted">Based on your quotation template: company header, quotation details, customer type, payment terms, salesperson, PO, shipping info, item table, totals, terms and acceptance section.</p><span class="status green">Template Applied</span></div></div>'+ 
'<div class="card" style="margin-top:16px"><h3>Quotation Items</h3><table><thead><tr><th>No</th><th>Model/Product Code</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Tax</th><th>Amount</th><th>Action</th></tr></thead><tbody id="quoteLineBody"></tbody></table><div class="actions"><button class="primary" id="saveQuote">Save Quotation</button><button class="secondary" id="clearLines">Clear Items</button></div></div><div id="docArea"></div>');renderQuoteLines();document.getElementById('addLine').onclick=addQuoteLine;document.getElementById('clearLines').onclick=function(){quoteDraft=[];renderQuoteLines();};document.getElementById('saveQuote').onclick=saveQuote;}

function addQuoteLine(){var desc=lineDesc.value.trim();if(!desc){alert('Enter description');return;}var model=(lineModel.value||'').trim();var qty=Number(lineQty.value)||0,price=Number(linePrice.value)||0,discount=Number(lineDiscount.value)||0,taxRate=Number(lineTax.value)||0;var sub=(qty*price)-discount;var tax=Math.max(sub,0)*taxRate/100;var total=Math.max(sub,0)+tax;quoteDraft.push({model:model,desc:desc,qty:qty,price:price,discount:discount,taxRate:taxRate,tax:tax,total:total});lineModel.value='';lineDesc.value='';lineQty.value=1;linePrice.value='';lineDiscount.value=0;lineTax.value=0;renderQuoteLines();}

function renderQuoteLines(){var body=document.getElementById('quoteLineBody');if(!body)return;body.innerHTML=quoteDraft.map(function(l,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(l.model||'')+'</td><td>'+esc(l.desc)+'</td><td>'+l.qty+'</td><td>'+money(l.price)+'</td><td>'+(l.taxRate?l.taxRate+'%':'N')+'</td><td>'+money(l.total)+'</td><td><button class="danger" data-remove-line="'+i+'">Remove</button></td></tr>';}).join('')||'<tr><td colspan="8">No items yet.</td></tr>';body.querySelectorAll('[data-remove-line]').forEach(function(b){b.onclick=function(){quoteDraft.splice(Number(b.getAttribute('data-remove-line')),1);renderQuoteLines();};});}

function saveQuote(){if(!qCustomer.value){alert('Select customer');return;}if(!quoteDraft.length){alert('Add at least one line item');return;}var subtotal=quoteDraft.reduce(function(s,l){return s+(l.qty*l.price);},0),discount=quoteDraft.reduce(function(s,l){return s+l.discount;},0),taxAmount=quoteDraft.reduce(function(s,l){return s+l.tax;},0),grandTotal=quoteDraft.reduce(function(s,l){return s+l.total;},0);var rec=DB.add('quotations',{no:stamp('quotations','QT'),flowStatus:'Quotation Created',customerId:qCustomer.value,projectId:qProject.value,quotationFor:qFor.value,customerType:qCustomerType.value,paymentTerms:qPaymentTerms.value,salesperson:qSalesperson.value,poNumber:qPoNumber.value,shipDate:qShipDate.value,shipVia:qShipVia.value,terms:qTerms.value,items:quoteDraft.slice(),subtotal:subtotal,discount:discount,taxAmount:taxAmount,grandTotal:grandTotal,status:qStatus.value,remark:qRemark.value,validUntil:qValid.value,date:new Date().toLocaleDateString()});quoteDraft=[];renderCommerce('quotations');setTimeout(function(){showDoc('quotation',rec.id);},100);}

function commerceQuotationList(){var rows=DB.get('quotations').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+projectName(x.projectId)+'</td><td>'+((x.items||[]).length||1)+'</td><td>'+money(x.grandTotal)+'</td><td><span class="status green">'+esc(x.flowStatus||'Quotation Created')+'</span></td><td><button class="secondary" data-doc="quotation" data-id="'+x.id+'">Preview</button> <button class="secondary" data-do="'+x.id+'">Create DO</button> <button class="secondary" data-inv="'+x.id+'">Invoice</button></td></tr>';}).join('');commerceLayout('quotations',flowLine('Quotations')+'<button class="primary" data-commerce-tab="create-quotation">+ New Quotation</button>'+table('Quotations',rows,['No','Customer','Project','Items','Total','Flow Status','Actions'])+'<div id="docArea"></div>');bindDocButtons();}
function commerceDeliveryOrders(){var rows=DB.get('deliveryOrders').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td><span class="status green">DO Created</span></td><td><button class="secondary" data-doc="delivery" data-id="'+x.id+'">Preview</button> <button class="secondary" data-inv-from-do="'+x.id+'">Create Invoice</button></td></tr>';}).join('');commerceLayout('delivery-orders',flowLine('Delivery Orders')+table('Delivery Orders',rows,['No','Customer','Flow Status','Action'])+'<div id="docArea"></div>');bindDocButtons();}
function commerceInvoices(){var rows=DB.get('invoices').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+money(x.grandTotal)+'</td><td>'+money(x.balance)+'</td><td><span class="status '+(x.status==='Paid'?'green':'orange')+'">'+x.status+'</span></td><td><button class="secondary" data-doc="invoice" data-id="'+x.id+'">Preview</button> <button class="secondary" data-pay-invoice="'+x.id+'">Pay</button></td></tr>';}).join('');commerceLayout('invoices',flowLine('Invoices')+table('Invoices',rows,['No','Customer','Total','Balance','Status','Action'])+'<div id="docArea"></div>');bindDocButtons();document.querySelectorAll('[data-pay-invoice]').forEach(function(b){b.onclick=function(){renderCommerce('payments');setTimeout(function(){var sel=document.getElementById('payInvoice');if(sel)sel.value=b.getAttribute('data-pay-invoice');},50);};});}
function commercePayments(){commerceLayout('payments',flowLine('Payments')+'<div class="card"><h3>Record Payment</h3><select id="payInvoice">'+invoiceOptions()+'</select><div class="row"><input id="payAmount" type="number" placeholder="Payment Amount"><select id="payMethod"><option>Bank Transfer</option><option>Cash</option><option>DuitNow</option><option>Cheque</option></select></div><input id="payRef" placeholder="Reference No" style="margin-top:12px"><button class="primary" id="recordPayment" style="margin-top:12px">Save Payment + Generate Receipt</button></div>'+table('Payments',DB.get('payments').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+money(x.amount)+'</td><td>'+x.method+'</td><td>'+(x.reference||'-')+'</td></tr>';}).join(''),['No','Customer','Amount','Method','Reference'])+'<div id="docArea"></div>');document.getElementById('recordPayment').onclick=recordPayment;}
function commerceReceipts(){var rows=DB.get('receipts').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+money(x.amount)+'</td><td>'+x.method+'</td><td><span class="status green">Receipt Generated</span></td><td><button class="secondary" data-doc="receipt" data-id="'+x.id+'">Preview</button></td></tr>';}).join('');commerceLayout('receipts',flowLine('Official Receipts')+table('Official Receipts',rows,['No','Customer','Amount','Method','Flow Status','Action'])+'<div id="docArea"></div>');bindDocButtons();}
function commerceStatements(){var rows=DB.get('customers').map(function(c){return '<tr><td>'+esc(c.name)+'</td><td>'+DB.get('invoices').filter(function(i){return i.customerId===c.id;}).length+'</td><td>'+DB.get('receipts').filter(function(r){return r.customerId===c.id;}).length+'</td><td><button class="secondary" data-statement="'+c.id+'">Statement</button></td></tr>';}).join('');commerceLayout('statements',table('Customers',rows,['Customer','Invoices','Receipts','Action'])+'<div id="docArea"></div>');document.querySelectorAll('[data-statement]').forEach(function(b){b.onclick=function(){showStatement(b.getAttribute('data-statement'));};});}
function commerceTemplates(){commerceLayout('templates','<div class="cards">'+[['quotation','Quotation Template'],['delivery','Delivery Order Template'],['invoice','Invoice Template'],['receipt','Official Receipt Template'],['statement','Customer Statement Template']].map(function(t){return '<div class="module template-card" data-template="'+t[0]+'"><h3>'+t[1]+'</h3><span class="status green">Accessible</span><p class="muted">Click to preview '+t[1]+'.</p></div>';}).join('')+'</div><div id="templatePreview"></div>');document.querySelectorAll('[data-template]').forEach(function(b){b.onclick=function(){previewTemplate(b.getAttribute('data-template'));};});}
function invoiceOptions(){return '<option value="">-- Select Invoice --</option>'+DB.get('invoices').filter(function(i){return i.status!=='Paid';}).map(function(i){return '<option value="'+i.id+'">'+i.no+' - '+customerName(i.customerId)+' - Balance '+money(i.balance)+'</option>';}).join('');}
function bindDocButtons(){document.querySelectorAll('[data-doc]').forEach(function(b){b.onclick=function(){showDoc(b.getAttribute('data-doc'),b.getAttribute('data-id'));};});document.querySelectorAll('[data-do]').forEach(function(b){b.onclick=function(){createDO(b.getAttribute('data-do'));};});document.querySelectorAll('[data-inv]').forEach(function(b){b.onclick=function(){createInvoiceFromQuote(b.getAttribute('data-inv'));};});document.querySelectorAll('[data-inv-from-do]').forEach(function(b){b.onclick=function(){createInvoiceFromDO(b.getAttribute('data-inv-from-do'));};});}
function createDO(id){var q=DB.get('quotations').find(function(x){return x.id===id;});if(!q)return;DB.update('quotations',id,{flowStatus:'DO Created',status:'Approved'});var d=DB.add('deliveryOrders',{no:stamp('deliveryOrders','DO'),quotationId:id,customerId:q.customerId,projectId:q.projectId,items:q.items||[],status:'Issued',date:new Date().toLocaleDateString()});renderCommerce('delivery-orders');setTimeout(function(){showDoc('delivery',d.id);},100);}
function createInvoiceFromQuote(id){var q=DB.get('quotations').find(function(x){return x.id===id;});if(!q)return;DB.update('quotations',id,{flowStatus:'Invoice Created'});var inv=DB.add('invoices',{no:stamp('invoices','INV'),quotationId:id,customerId:q.customerId,projectId:q.projectId,items:q.items||[],subtotal:q.subtotal,discount:q.discount,taxAmount:q.taxAmount,grandTotal:q.grandTotal,paid:0,balance:q.grandTotal,status:'Issued',date:new Date().toLocaleDateString()});renderCommerce('invoices');setTimeout(function(){showDoc('invoice',inv.id);},100);}
function createInvoiceFromDO(id){var d=DB.get('deliveryOrders').find(function(x){return x.id===id;});if(!d)return;var q=d.quotationId?DB.get('quotations').find(function(x){return x.id===d.quotationId;}):null;if(q)DB.update('quotations',q.id,{flowStatus:'Invoice Created'});var inv=DB.add('invoices',{no:stamp('invoices','INV'),deliveryOrderId:id,quotationId:d.quotationId,customerId:d.customerId,projectId:d.projectId,items:d.items||[],subtotal:q?q.subtotal:0,discount:q?q.discount:0,taxAmount:q?q.taxAmount:0,grandTotal:q?q.grandTotal:0,paid:0,balance:q?q.grandTotal:0,status:'Issued',date:new Date().toLocaleDateString()});renderCommerce('invoices');setTimeout(function(){showDoc('invoice',inv.id);},100);}
function recordPayment(){var inv=DB.get('invoices').find(function(x){return x.id===payInvoice.value;});if(!inv){alert('Select invoice');return;}var amt=Number(payAmount.value)||0;if(amt<=0){alert('Enter amount');return;}var paid=(Number(inv.paid)||0)+amt,balance=Math.max((Number(inv.grandTotal)||0)-paid,0),status=balance<=0?'Paid':'Partially Paid';DB.update('invoices',inv.id,{paid:paid,balance:balance,status:status});if(inv.quotationId)DB.update('quotations',inv.quotationId,{flowStatus:'Official Receipt Generated'});var pay=DB.add('payments',{no:stamp('payments','PAY'),invoiceId:inv.id,customerId:inv.customerId,amount:amt,method:payMethod.value,reference:payRef.value,date:new Date().toLocaleDateString()});var r=DB.add('receipts',{no:stamp('receipts','RCP'),paymentId:pay.id,invoiceId:inv.id,customerId:inv.customerId,amount:amt,method:payMethod.value,reference:payRef.value,status:'Issued',date:new Date().toLocaleDateString()});renderCommerce('receipts');setTimeout(function(){showDoc('receipt',r.id);},100);}
function docTitle(type){return {quotation:'QUOTATION',delivery:'DELIVERY ORDER',invoice:'INVOICE',receipt:'OFFICIAL RECEIPT',statement:'CUSTOMER STATEMENT'}[type]||'DOCUMENT';}
function docRecord(type,id){var map={quotation:'quotations',delivery:'deliveryOrders',invoice:'invoices',receipt:'receipts'};return DB.get(map[type]).find(function(x){return x.id===id;});}
function sample(type){var items=[{desc:'Website UI Design',qty:1,price:2500,discount:0,tax:0,total:2500},{desc:'Deployment & Testing',qty:1,price:1500,discount:0,tax:0,total:1500}];return {no:type.toUpperCase()+'-SAMPLE-001',items:items,subtotal:4000,discount:0,taxAmount:0,grandTotal:4000,amount:4000,paid:0,balance:4000,status:'Sample',date:new Date().toLocaleDateString(),method:'Bank Transfer',reference:'SAMPLE'};}
function previewTemplate(type){var area=document.getElementById('templatePreview');area.innerHTML='<div class="doc-shell print-card"><div class="no-print actions"><button class="primary" onclick="window.print()">Print Template</button></div>'+documentHtml(type,sample(type))+'</div>';area.scrollIntoView({behavior:'smooth'});}
function showDoc(type,id){var rec=docRecord(type,id);if(!rec){alert('Document not found');return;}var area=document.getElementById('docArea');area.innerHTML='<div class="doc-shell print-card"><div class="no-print actions"><button class="primary" onclick="window.print()">Print</button><button class="secondary" onclick="shareWhatsApp(\''+type+'\',\''+rec.no+'\')">WhatsApp</button></div>'+documentHtml(type,rec)+'</div>';area.scrollIntoView({behavior:'smooth'});}
function documentHtml(type,rec){var s=DB.get('settings'),items=rec.items||[],isDO=type==='delivery',isStatement=type==='statement';var subtotal=rec.subtotal||items.reduce(function(a,b){return a+(b.qty*b.price);},0),discount=rec.discount||0,tax=rec.taxAmount||0,total=rec.grandTotal||rec.amount||0;var quoteFor=rec.quotationFor||'Selected / Sample Customer';var terms=rec.terms||s.terms||'';return '<div class="document-preview"><div class="doc-top"><div class="doc-company"><div class="doc-logo">CP</div><div><h2>'+esc(s.company)+'</h2><p>Reg No: '+esc(s.ssm)+'<br>'+esc(s.address)+'<br>Contact Number: '+esc(s.phone||'')+'<br>Email: '+esc(s.email)+'</p></div></div><div class="doc-title"><h1>'+docTitle(type)+'</h1><p><b>No:</b> '+esc(rec.no)+'<br><b>Date:</b> '+esc(rec.date||new Date().toLocaleDateString())+'</p><span class="doc-badge">'+esc(rec.status||'Issued')+'</span></div></div><div class="doc-meta"><div class="doc-box"><b>'+docTitle(type)+' FOR</b><p>'+esc(quoteFor)+'<br>'+esc(customerName(rec.customerId))+'</p></div><div class="doc-box"><b>Customer / Payment</b><p><b>Customer Type:</b> '+esc(rec.customerType||'Corporate')+'<br><b>Payment Terms:</b> '+esc(rec.paymentTerms||'Online Banking')+'</p></div></div><div class="doc-meta-compact"><div class="doc-box"><b>Salesperson</b><br>'+esc(rec.salesperson||s.preparedBy||'-')+'</div><div class="doc-box"><b>P.O. Number</b><br>'+esc(rec.poNumber||'N/A')+'</div><div class="doc-box"><b>Ship Date</b><br>'+esc(rec.shipDate||'—')+'</div><div class="doc-box"><b>Ship Via</b><br>'+esc(rec.shipVia||'—')+'</div><div class="doc-box"><b>Project / Reference</b><br>'+esc(projectName(rec.projectId))+'</div><div class="doc-box"><b>Prepared By</b><br>'+esc(s.preparedBy||'-')+'</div></div>'+(isDO?doItems(items):isStatement?statementItems():normalItems(items))+(isDO||isStatement?'':summary(subtotal,discount,tax,total,type,rec))+'<div class="terms"><b>'+(isDO?'Delivery Notes':'TERMS & CONDITIONS')+'</b><div class="doc-terms-block">'+esc(isDO?'Goods/services received in good condition unless stated otherwise.':terms)+'</div></div><div class="signature"><div><div class="sig-line">Quotation Prepared By</div><p class="muted">'+esc(s.company)+'<br>'+esc(rec.salesperson||s.preparedBy||'')+'</p></div><div><div class="sig-line">Confirmed & Accepted By</div><p class="muted">Customer Name: ____________________<br>Signature & Stamp: ____________________</p></div></div><div class="doc-footer">'+esc(s.company)+' — '+esc(s.ssm)+' • '+esc(rec.no)+' • '+esc(rec.date||new Date().toLocaleDateString())+'</div></div>';}

function normalItems(items){return '<table class="doc-table"><thead><tr><th>No</th><th>Model/Product Code</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Tax</th><th>Amount</th></tr></thead><tbody>'+items.map(function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.model||'')+'</td><td>'+esc(x.desc)+'</td><td>'+x.qty+'</td><td>'+money(x.price)+'</td><td>'+(x.taxRate?x.taxRate+'%':'N')+'</td><td>'+money(x.total)+'</td></tr>';}).join('')+'</tbody></table>';}

function doItems(items){return '<table class="doc-table do-table"><thead><tr><th>No</th><th>Model/Product Code</th><th>Item / Description</th><th>Quantity</th><th>Unit</th><th>Remarks</th></tr></thead><tbody>'+items.map(function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.model||'')+'</td><td>'+esc(x.desc)+'</td><td>'+x.qty+'</td><td>Lot</td><td>Delivered as per quotation</td></tr>';}).join('')+'</tbody></table>';}

function statementItems(){return '<table class="doc-table"><thead><tr><th>Date</th><th>Document</th><th>Debit</th><th>Credit</th></tr></thead><tbody><tr><td>'+new Date().toLocaleDateString()+'</td><td>INV-SAMPLE-001</td><td>'+money(4000)+'</td><td>-</td></tr><tr><td>'+new Date().toLocaleDateString()+'</td><td>RCP-SAMPLE-001</td><td>-</td><td>'+money(2000)+'</td></tr></tbody></table><div class="doc-summary"><div><span>Total Invoices</span><b>'+money(4000)+'</b></div><div><span>Total Payments</span><b>'+money(2000)+'</b></div><div class="grand"><span>Balance</span><b>'+money(2000)+'</b></div></div>';}
function summary(subtotal,discount,tax,total,type,rec){return '<div class="doc-summary doc-total-box"><div class="doc-total-row"><span>Subtotal</span><b>'+money(subtotal)+'</b></div><div class="doc-total-row"><span>Tax</span><b>'+money(tax)+'</b></div><div class="doc-total-row"><span>Discount</span><b>'+money(discount)+'</b></div><div class="doc-total-row total"><span>TOTAL</span><b>'+money(total)+'</b></div>'+(type==='invoice'?'<div class="doc-total-row"><span>Paid</span><b>'+money(rec.paid)+'</b></div><div class="doc-total-row"><span>Balance</span><b>'+money(rec.balance)+'</b></div>':'')+(type==='receipt'?'<div class="doc-total-row"><span>Payment Method</span><b>'+esc(rec.method||'-')+'</b></div><div class="doc-total-row"><span>Reference</span><b>'+esc(rec.reference||'-')+'</b></div>':'')+'</div>';}

function showStatement(customerId){renderCommerce('statements');}
function simpleModule(key){var label=(modules.find(function(m){return m[0]===key;})||['',key])[1];app.innerHTML=pageHead(label,'All buttons in this module are accessible.')+subnav(key)+'<div class="cards">'+(moduleSubs[key]||[]).map(function(s){return '<div class="module" data-sub="'+esc(s)+'" data-module="'+esc(key)+'"><h3>'+esc(s)+'</h3><span class="status green">Accessible</span><p class="muted">Click to open '+esc(s)+'.</p></div>';}).join('')+'</div>';}
['website','support','assets','vendors','employees','documents','reports','audit','settings'].forEach(function(k){pages[k]=function(){simpleModule(k);};});pages.generic=function(k){simpleModule(k);};
renderNav();route('dashboard');
})();
