(function(){
var app=document.getElementById('app');
var title=document.getElementById('pageTitle');
var nav=document.getElementById('nav');
var menuBtn=document.getElementById('menuBtn');
if(menuBtn){menuBtn.addEventListener('click',function(){document.getElementById('sidebar').classList.toggle('open');});}

var modules=[
 ['dashboard','Dashboard'],['crm','Customer CRM'],['projects','Project Management'],['commerce','Commerce Core'],['quotation-list','Quotations'],['quotation-create','Create Quotation'],['delivery-orders','Delivery Orders'],['invoices','Invoices'],['payments','Payments'],['receipts','Official Receipts'],['statements','Customer Statements'],['templates','Document Templates'],['website','Website Builder'],['support','Support Center'],['assets','Asset Management'],['vendors','Vendor Management'],['employees','Employee Management'],['documents','Document Repository'],['reports','Reports & Analytics'],['audit','Audit Logs'],['settings','Settings']
];
var moduleSubs={
 dashboard:['KPIs','Quick Actions','Recent Activities','Module Launcher'],
 crm:['Customers','Leads','Prospects','Customer Profiles','Contact History','Financial Summary','Customer Statement'],
 projects:['Project Creation','Customer Linked Projects','Budget Tracking','Cost Tracking','Profitability','Tasks','Milestones','Files'],
 commerce:['Quotations','Create Quotation','Delivery Orders','Invoices','Payments','Official Receipts','Customer Statements','Templates'],
 website:['Website Projects','Domains','Hosting','Deployment','SEO','Maintenance'],
 support:['Tickets','Customer Support','Project Support','Resolution Tracking','SLA Monitoring'],
 assets:['Assets','Serial Numbers','Assignment','Maintenance','Warranty'],
 vendors:['Vendors','Procurement','Rating','Purchase Tracking','Contracts'],
 employees:['Employees','Roles','Departments','Assignments','Performance'],
 documents:['Customer Documents','Project Documents','Finance Documents','Internal Documents','Templates'],
 reports:['Revenue','Outstanding','Customer Value','Cash Flow','Profit & Loss','Project Profitability'],
 audit:['CRM Logs','Project Logs','Commerce Logs','Settings Logs','System Logs'],
 settings:['Company Profile','Logo','SSM Number','Bank Details','Terms & Conditions','Tax Settings','Document Prefixes','Backup Export','Restore Data']
};
var templateTypes=[['quotation','Quotation Template'],['delivery','Delivery Order Template'],['invoice','Invoice Template'],['receipt','Official Receipt Template'],['statement','Customer Statement Template']];
var quoteDraft=[];

function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function money(v){return 'RM '+(Number(v)||0).toFixed(2);}
function stamp(k,p){return p+'-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'-'+String(DB.get(k).length+1).padStart(3,'0');}
function customerName(id){var x=DB.get('customers').find(function(c){return c.id===id;});return x?x.name:'Unlinked / Manual';}
function projectName(id){var x=DB.get('projects').find(function(p){return p.id===id;});return x?x.name:'-';}
function customerOptions(){return '<option value="">-- Select Customer --</option>'+DB.get('customers').map(function(c){return '<option value="'+c.id+'">'+esc(c.name)+'</option>';}).join('');}
function projectOptions(){return '<option value="">-- Select Project --</option>'+DB.get('projects').map(function(p){return '<option value="'+p.id+'">'+esc(p.name)+' - '+esc(customerName(p.customerId))+'</option>';}).join('');}
function pageHead(t,d,a){title.textContent=t;return '<div class="page-head"><div><h2>'+esc(t)+'</h2><p class="muted">'+esc(d)+'</p></div>'+(a||'')+'</div>';}
function table(titleText,rows,cols){return '<div class="card" style="margin-top:16px"><h3>'+esc(titleText)+'</h3><table><thead><tr>'+cols.map(function(c){return '<th>'+esc(c)+'</th>';}).join('')+'</tr></thead><tbody>'+(rows||'<tr><td colspan="'+cols.length+'">No records yet.</td></tr>')+'</tbody></table></div>';}
function subnav(key){var list=moduleSubs[key]||[];return '<div class="subnav">'+list.map(function(s){return '<button type="button" data-sub="'+esc(s)+'" data-module="'+esc(key)+'">'+esc(s)+'</button>';}).join('')+'</div>';}
function commerceSubnav(){return '<div class="subnav"><button data-route="quotation-list">Quotations</button><button data-route="quotation-create">Create Quotation</button><button data-route="delivery-orders">Delivery Orders</button><button data-route="invoices">Invoices</button><button data-route="payments">Payments</button><button data-route="receipts">Official Receipts</button><button data-route="statements">Customer Statements</button><button data-route="templates">Templates</button></div>';}

function renderNav(){nav.innerHTML=modules.map(function(m,i){return '<button type="button" class="'+(i===0?'active':'')+'" data-route="'+m[0]+'">'+m[1]+'</button>';}).join('');}
function route(key){document.querySelectorAll('#nav button').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-route')===key);});(pages[key]||pages.generic)(key);var sidebar=document.getElementById('sidebar');if(sidebar)sidebar.classList.remove('open');}
window.go=route;

document.addEventListener('click',function(e){var r=e.target.getAttribute&&e.target.getAttribute('data-route');if(r){route(r);}var sub=e.target.getAttribute&&e.target.getAttribute('data-sub');if(sub){openSub(e.target.getAttribute('data-module'),sub);}});

function openSub(mod,sub){if(sub==='Templates'){route('templates');return;}app.innerHTML=pageHead(sub,(modules.find(function(m){return m[0]===mod;})||['',mod])[1]+' submodule is accessible.','<button class="secondary" data-route="'+mod+'">Back</button>')+'<div class="card"><h3>'+esc(sub)+'</h3><p class="muted">This button is working and this submodule page is accessible. Detailed forms can be expanded in the next sprint.</p><span class="status green">Accessible</span></div>';}

var pages={};
pages.dashboard=function(){var c=DB.get('customers'),p=DB.get('projects'),q=DB.get('quotations'),i=DB.get('invoices');app.innerHTML=pageHead('Dashboard','Fresh rebuild from the beginning. Login removed. All modules and templates accessible.')+subnav('dashboard')+'<div class="grid"><div class="card"><span class="muted">Customers</span><div class="metric">'+c.length+'</div></div><div class="card"><span class="muted">Projects</span><div class="metric">'+p.length+'</div></div><div class="card"><span class="muted">Quotations</span><div class="metric">'+q.length+'</div></div><div class="card"><span class="muted">Invoices</span><div class="metric">'+i.length+'</div></div></div><div class="cards">'+modules.filter(function(m){return m[0]!=='dashboard';}).map(function(m){return '<div class="module" data-route="'+m[0]+'"><h3>'+m[1]+'</h3><span class="status green">Accessible</span><p class="muted">Open '+m[1]+'.</p></div>';}).join('')+'</div>';};

pages.crm=function(){var rows=DB.get('customers').map(function(c){return '<tr><td>'+esc(c.name)+'</td><td>'+esc(c.phone||'-')+'</td><td>'+esc(c.email||'-')+'</td></tr>';}).join('');app.innerHTML=pageHead('Customer CRM','Create and manage customer records.')+subnav('crm')+'<div class="card"><h3>Add Customer</h3><div class="row"><input id="cName" placeholder="Customer / Company"><input id="cPhone" placeholder="Phone"></div><div class="row"><input id="cEmail" placeholder="Email"><input id="cAddress" placeholder="Address"></div><div class="actions"><button class="primary" id="saveCustomer">Save Customer</button></div></div>'+table('Customers',rows,['Name','Phone','Email']);document.getElementById('saveCustomer').onclick=function(){var n=document.getElementById('cName').value.trim();if(!n){alert('Enter customer name');return;}DB.add('customers',{name:n,phone:cPhone.value,email:cEmail.value,address:cAddress.value});route('crm');};};

pages.projects=function(){var rows=DB.get('projects').map(function(p){return '<tr><td>'+esc(p.name)+'</td><td>'+esc(customerName(p.customerId))+'</td><td>'+esc(p.type)+'</td></tr>';}).join('');app.innerHTML=pageHead('Project Management','Create projects linked to customers.')+subnav('projects')+'<div class="card"><h3>Create Project</h3><div class="row3"><input id="pName" placeholder="Project Name"><select id="pCustomer">'+customerOptions()+'</select><select id="pType"><option>Website</option><option>App</option><option>CCTV</option><option>Networking</option><option>Consultancy</option></select></div><div class="actions"><button class="primary" id="saveProject">Save Project</button></div></div>'+table('Projects',rows,['Project','Customer','Type']);document.getElementById('saveProject').onclick=function(){if(!pName.value.trim()||!pCustomer.value){alert('Enter project and customer');return;}DB.add('projects',{name:pName.value,customerId:pCustomer.value,type:pType.value,status:'Active'});route('projects');};};

pages.commerce=function(){app.innerHTML=pageHead('Commerce Core','Separate commerce pages and templates are accessible.')+commerceSubnav()+'<div class="cards"><div class="module" data-route="quotation-create"><h3>Create Quotation</h3></div><div class="module" data-route="quotation-list"><h3>Quotations</h3></div><div class="module" data-route="delivery-orders"><h3>Delivery Orders</h3></div><div class="module" data-route="invoices"><h3>Invoices</h3></div><div class="module" data-route="payments"><h3>Payments</h3></div><div class="module" data-route="receipts"><h3>Receipts</h3></div><div class="module" data-route="statements"><h3>Customer Statements</h3></div><div class="module template-card" data-route="templates"><h3>Document Templates</h3><span class="status green">Accessible</span></div></div>';};

pages['quotation-create']=function(){app.innerHTML=pageHead('Create Quotation','Add multiple task/description line items.','<button class="secondary" data-route="quotation-list">Quotation List</button>')+commerceSubnav()+'<div class="grid2"><div class="card"><h3>Quotation Header</h3><div class="row"><select id="qCustomer">'+customerOptions()+'</select><select id="qProject">'+projectOptions()+'</select></div><div class="row3"><input id="qValid" type="date"><select id="qStatus"><option>Draft</option><option>Sent</option><option>Approved</option></select><input id="qRemark" placeholder="Remark"></div></div><div class="card"><h3>Add Task / Description</h3><textarea id="lineDesc" placeholder="Task / Description"></textarea><div class="row3"><input id="lineQty" type="number" value="1"><input id="linePrice" type="number" placeholder="Unit Price RM"><input id="lineDiscount" type="number" value="0"></div><div class="row"><input id="lineTax" type="number" value="0"><button class="primary" id="addLine">+ Add Item</button></div></div></div><div class="card" style="margin-top:16px"><h3>Quotation Items</h3><table><thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Discount</th><th>Tax</th><th>Total</th><th>Action</th></tr></thead><tbody id="quoteLineBody"></tbody></table><div class="actions"><button class="primary" id="saveQuote">Save Quotation</button><button class="secondary" id="clearLines">Clear Items</button></div></div><div id="docArea"></div>';renderQuoteLines();document.getElementById('addLine').onclick=addQuoteLine;document.getElementById('clearLines').onclick=function(){quoteDraft=[];renderQuoteLines();};document.getElementById('saveQuote').onclick=saveQuotation;};
function addQuoteLine(){var desc=lineDesc.value.trim();if(!desc){alert('Enter task/description');return;}var qty=Number(lineQty.value)||1,price=Number(linePrice.value)||0,discount=Number(lineDiscount.value)||0,taxRate=Number(lineTax.value)||0;var sub=(qty*price)-discount;var tax=Math.max(sub,0)*taxRate/100;var total=Math.max(sub,0)+tax;quoteDraft.push({desc:desc,qty:qty,price:price,discount:discount,taxRate:taxRate,tax:tax,total:total});lineDesc.value='';lineQty.value=1;linePrice.value='';lineDiscount.value=0;lineTax.value=0;renderQuoteLines();}
function renderQuoteLines(){var body=document.getElementById('quoteLineBody');if(!body)return;body.innerHTML=quoteDraft.map(function(l,i){return '<tr><td>'+esc(l.desc)+'</td><td>'+l.qty+'</td><td>'+money(l.price)+'</td><td>'+money(l.discount)+'</td><td>'+money(l.tax)+'</td><td>'+money(l.total)+'</td><td><button class="danger" data-remove-line="'+i+'">Remove</button></td></tr>';}).join('')||'<tr><td colspan="7">No items yet.</td></tr>';body.querySelectorAll('[data-remove-line]').forEach(function(b){b.onclick=function(){quoteDraft.splice(Number(b.getAttribute('data-remove-line')),1);renderQuoteLines();};});}
function saveQuotation(){if(!qCustomer.value){alert('Select customer');return;}if(!quoteDraft.length){alert('Add at least one item');return;}var subtotal=quoteDraft.reduce(function(s,l){return s+(l.qty*l.price);},0),discount=quoteDraft.reduce(function(s,l){return s+l.discount;},0),taxAmount=quoteDraft.reduce(function(s,l){return s+l.tax;},0),grandTotal=quoteDraft.reduce(function(s,l){return s+l.total;},0);var rec=DB.add('quotations',{no:stamp('quotations','QT'),customerId:qCustomer.value,projectId:qProject.value,items:quoteDraft.slice(),subtotal:subtotal,discount:discount,taxAmount:taxAmount,grandTotal:grandTotal,status:qStatus.value,remark:qRemark.value,validUntil:qValid.value,date:new Date().toLocaleDateString()});quoteDraft=[];route('quotation-list');setTimeout(function(){showDoc('quotation',rec.id);},100);}

pages['quotation-list']=function(){var rows=DB.get('quotations').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+projectName(x.projectId)+'</td><td>'+((x.items||[]).length||1)+'</td><td>'+money(x.grandTotal)+'</td><td>'+x.status+'</td><td><button class="secondary" data-doc="quotation" data-id="'+x.id+'">Preview</button> <button class="secondary" data-do="'+x.id+'">Create DO</button> <button class="secondary" data-inv="'+x.id+'">Invoice</button></td></tr>';}).join('');app.innerHTML=pageHead('Quotation List','Manage quotations.','<button class="primary" data-route="quotation-create">+ New Quotation</button>')+commerceSubnav()+table('Quotations',rows,['No','Customer','Project','Items','Total','Status','Actions'])+'<div id="docArea"></div>';bindDocButtons();};
pages['delivery-orders']=function(){var rows=DB.get('deliveryOrders').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+x.status+'</td><td><button class="secondary" data-doc="delivery" data-id="'+x.id+'">Preview</button></td></tr>';}).join('');app.innerHTML=pageHead('Delivery Orders','Delivery orders are accessible.')+commerceSubnav()+table('Delivery Orders',rows,['No','Customer','Status','Action'])+'<div id="docArea"></div>';bindDocButtons();};
pages.invoices=function(){var rows=DB.get('invoices').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+money(x.grandTotal)+'</td><td>'+money(x.balance)+'</td><td>'+x.status+'</td><td><button class="secondary" data-doc="invoice" data-id="'+x.id+'">Preview</button></td></tr>';}).join('');app.innerHTML=pageHead('Invoices','Invoices are accessible.')+commerceSubnav()+table('Invoices',rows,['No','Customer','Total','Balance','Status','Action'])+'<div id="docArea"></div>';bindDocButtons();};
pages.payments=function(){app.innerHTML=pageHead('Payments','Record invoice payments.')+commerceSubnav()+'<div class="card"><h3>Record Payment</h3><select id="payInvoice">'+invoiceOptions()+'</select><div class="row"><input id="payAmount" type="number" placeholder="Payment Amount"><select id="payMethod"><option>Bank Transfer</option><option>Cash</option><option>DuitNow</option><option>Cheque</option></select></div><input id="payRef" placeholder="Reference No" style="margin-top:12px"><button class="primary" id="recordPayment" style="margin-top:12px">Save Payment + Receipt</button></div>'+table('Payments',DB.get('payments').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+money(x.amount)+'</td><td>'+x.method+'</td><td>'+(x.reference||'-')+'</td></tr>';}).join(''),['No','Customer','Amount','Method','Reference'])+'<div id="docArea"></div>';document.getElementById('recordPayment').onclick=recordPayment;};
pages.receipts=function(){var rows=DB.get('receipts').map(function(x){return '<tr><td>'+x.no+'</td><td>'+customerName(x.customerId)+'</td><td>'+money(x.amount)+'</td><td>'+x.method+'</td><td><button class="secondary" data-doc="receipt" data-id="'+x.id+'">Preview</button></td></tr>';}).join('');app.innerHTML=pageHead('Official Receipts','Receipts are accessible.')+commerceSubnav()+table('Receipts',rows,['No','Customer','Amount','Method','Action'])+'<div id="docArea"></div>';bindDocButtons();};
pages.statements=function(){var rows=DB.get('customers').map(function(c){return '<tr><td>'+esc(c.name)+'</td><td>'+DB.get('invoices').filter(function(i){return i.customerId===c.id;}).length+'</td><td>'+DB.get('receipts').filter(function(r){return r.customerId===c.id;}).length+'</td><td><button class="secondary" data-statement="'+c.id+'">Statement</button></td></tr>';}).join('');app.innerHTML=pageHead('Customer Statements','Generate customer statements.')+commerceSubnav()+table('Customers',rows,['Customer','Invoices','Receipts','Action'])+'<div id="docArea"></div>';document.querySelectorAll('[data-statement]').forEach(function(b){b.onclick=function(){showStatement(b.getAttribute('data-statement'));};});};
pages.templates=function(){app.innerHTML=pageHead('Document Templates','All templates are accessible by clicking buttons.','<button class="secondary" data-route="commerce">Back to Commerce</button>')+'<div class="cards">'+templateTypes.map(function(t){return '<div class="module template-card" data-template="'+t[0]+'"><h3>'+t[1]+'</h3><span class="status green">Accessible</span><p class="muted">Click to preview '+t[1]+'.</p></div>';}).join('')+'</div><div id="templatePreview"></div>';document.querySelectorAll('[data-template]').forEach(function(b){b.onclick=function(){previewTemplate(b.getAttribute('data-template'));};});};
function invoiceOptions(){return '<option value="">-- Select Invoice --</option>'+DB.get('invoices').filter(function(i){return i.status!=='Paid';}).map(function(i){return '<option value="'+i.id+'">'+i.no+' - '+customerName(i.customerId)+' - Balance '+money(i.balance)+'</option>';}).join('');}
function bindDocButtons(){document.querySelectorAll('[data-doc]').forEach(function(b){b.onclick=function(){showDoc(b.getAttribute('data-doc'),b.getAttribute('data-id'));};});document.querySelectorAll('[data-do]').forEach(function(b){b.onclick=function(){createDO(b.getAttribute('data-do'));};});document.querySelectorAll('[data-inv]').forEach(function(b){b.onclick=function(){createInvoice(b.getAttribute('data-inv'));};});}
function createDO(id){var q=DB.get('quotations').find(function(x){return x.id===id;});if(!q)return;DB.update('quotations',id,{status:'Approved'});var d=DB.add('deliveryOrders',{no:stamp('deliveryOrders','DO'),quotationId:id,customerId:q.customerId,projectId:q.projectId,items:q.items||[],status:'Issued',date:new Date().toLocaleDateString()});route('delivery-orders');setTimeout(function(){showDoc('delivery',d.id);},100);}
function createInvoice(id){var q=DB.get('quotations').find(function(x){return x.id===id;});if(!q)return;var inv=DB.add('invoices',{no:stamp('invoices','INV'),quotationId:id,customerId:q.customerId,projectId:q.projectId,items:q.items||[],subtotal:q.subtotal,discount:q.discount,taxAmount:q.taxAmount,grandTotal:q.grandTotal,paid:0,balance:q.grandTotal,status:'Issued',date:new Date().toLocaleDateString()});route('invoices');setTimeout(function(){showDoc('invoice',inv.id);},100);}
function recordPayment(){var inv=DB.get('invoices').find(function(x){return x.id===payInvoice.value;});if(!inv){alert('Select invoice');return;}var amt=Number(payAmount.value)||0;if(amt<=0){alert('Enter amount');return;}var paid=(Number(inv.paid)||0)+amt,balance=Math.max((Number(inv.grandTotal)||0)-paid,0),status=balance<=0?'Paid':'Partially Paid';DB.update('invoices',inv.id,{paid:paid,balance:balance,status:status});var pay=DB.add('payments',{no:stamp('payments','PAY'),invoiceId:inv.id,customerId:inv.customerId,amount:amt,method:payMethod.value,reference:payRef.value,date:new Date().toLocaleDateString()});var r=DB.add('receipts',{no:stamp('receipts','RCP'),paymentId:pay.id,invoiceId:inv.id,customerId:inv.customerId,amount:amt,method:payMethod.value,reference:payRef.value,status:'Issued',date:new Date().toLocaleDateString()});route('receipts');setTimeout(function(){showDoc('receipt',r.id);},100);}
function docTitle(type){return {quotation:'QUOTATION',delivery:'DELIVERY ORDER',invoice:'INVOICE',receipt:'OFFICIAL RECEIPT',statement:'CUSTOMER STATEMENT'}[type]||'DOCUMENT';}
function docRecord(type,id){var map={quotation:'quotations',delivery:'deliveryOrders',invoice:'invoices',receipt:'receipts'};return DB.get(map[type]).find(function(x){return x.id===id;});}
function sample(type){var items=[{desc:'Website UI Design',qty:1,price:2500,discount:0,tax:0,total:2500},{desc:'Deployment & Testing',qty:1,price:1500,discount:0,tax:0,total:1500}];return {no:type.toUpperCase()+'-SAMPLE-001',items:items,subtotal:4000,discount:0,taxAmount:0,grandTotal:4000,amount:4000,paid:0,balance:4000,status:'Sample',date:new Date().toLocaleDateString(),method:'Bank Transfer',reference:'SAMPLE'};}
function previewTemplate(type){var area=document.getElementById('templatePreview');area.innerHTML='<div class="doc-shell print-card"><div class="no-print actions"><button class="primary" onclick="window.print()">Print Template</button><button class="secondary" data-route="templates">Back to Templates</button></div>'+documentHtml(type,sample(type))+'</div>';area.scrollIntoView({behavior:'smooth'});}
function showDoc(type,id){var rec=docRecord(type,id);if(!rec){alert('Document not found');return;}var area=document.getElementById('docArea');area.innerHTML='<div class="doc-shell print-card"><div class="no-print actions"><button class="primary" onclick="window.print()">Print</button><button class="secondary" onclick="shareWhatsApp(\''+type+'\',\''+rec.no+'\')">WhatsApp</button></div>'+documentHtml(type,rec)+'</div>';area.scrollIntoView({behavior:'smooth'});}
function documentHtml(type,rec){var s=DB.get('settings'),items=rec.items||[],isDO=type==='delivery',isStatement=type==='statement';var subtotal=rec.subtotal||items.reduce(function(a,b){return a+(b.qty*b.price);},0),discount=rec.discount||0,tax=rec.taxAmount||0,total=rec.grandTotal||rec.amount||0;return '<div class="document-preview"><div class="doc-top"><div class="doc-company"><div class="doc-logo">CP</div><div><h2>'+esc(s.company)+'</h2><p>Reg No: '+esc(s.ssm)+'<br>Email: '+esc(s.email)+'<br>'+esc(s.address)+'</p></div></div><div class="doc-title"><h1>'+docTitle(type)+'</h1><p><b>No:</b> '+esc(rec.no)+'<br><b>Date:</b> '+esc(rec.date||new Date().toLocaleDateString())+'</p><span class="doc-badge">'+esc(rec.status||'Issued')+'</span></div></div><div class="doc-meta"><div class="doc-box"><b>Customer</b><p>Sample / Selected Customer</p></div><div class="doc-box"><b>Project / Reference</b><p>Prepared By: '+esc(s.preparedBy||'-')+'</p></div></div>'+(isDO?doItems(items):isStatement?statementItems():normalItems(items))+(isDO||isStatement?'':summary(subtotal,discount,tax,total,type,rec))+'<div class="terms"><b>'+(isDO?'Delivery Notes':'Terms & Conditions')+'</b><p>'+(isDO?'Goods/services received in good condition unless stated otherwise.':esc(s.terms))+'</p></div><div class="signature"><div class="sig-line">Customer / Receiver</div><div class="sig-line">Authorised Signature</div></div><div class="doc-footer">Generated by ClientPro Hub • '+esc(s.company)+'</div></div>';}
function normalItems(items){return '<table class="doc-table"><thead><tr><th>No</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Discount</th><th>Tax</th><th>Total</th></tr></thead><tbody>'+items.map(function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.desc)+'</td><td>'+x.qty+'</td><td>'+money(x.price)+'</td><td>'+money(x.discount||0)+'</td><td>'+money(x.tax||0)+'</td><td>'+money(x.total)+'</td></tr>';}).join('')+'</tbody></table>';}
function doItems(items){return '<table class="doc-table do-table"><thead><tr><th>No</th><th>Item / Description</th><th>Quantity</th><th>Unit</th><th>Remarks</th></tr></thead><tbody>'+items.map(function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.desc)+'</td><td>'+x.qty+'</td><td>Lot</td><td>Delivered as per quotation</td></tr>';}).join('')+'</tbody></table>';}
function statementItems(){return '<table class="doc-table"><thead><tr><th>Date</th><th>Document</th><th>Debit</th><th>Credit</th></tr></thead><tbody><tr><td>'+new Date().toLocaleDateString()+'</td><td>INV-SAMPLE-001</td><td>'+money(4000)+'</td><td>-</td></tr><tr><td>'+new Date().toLocaleDateString()+'</td><td>RCP-SAMPLE-001</td><td>-</td><td>'+money(2000)+'</td></tr></tbody></table><div class="doc-summary"><div><span>Total Invoices</span><b>'+money(4000)+'</b></div><div><span>Total Payments</span><b>'+money(2000)+'</b></div><div class="grand"><span>Balance</span><b>'+money(2000)+'</b></div></div>';}
function summary(subtotal,discount,tax,total,type,rec){return '<div class="doc-summary"><div><span>Subtotal</span><b>'+money(subtotal)+'</b></div><div><span>Discount</span><b>'+money(discount)+'</b></div><div><span>Tax</span><b>'+money(tax)+'</b></div><div class="grand"><span>Grand Total</span><b>'+money(total)+'</b></div>'+(type==='invoice'?'<div><span>Paid</span><b>'+money(rec.paid)+'</b></div><div><span>Balance</span><b>'+money(rec.balance)+'</b></div>':'')+(type==='receipt'?'<div><span>Payment Method</span><b>'+esc(rec.method||'-')+'</b></div><div><span>Reference</span><b>'+esc(rec.reference||'-')+'</b></div>':'')+'</div>';}
window.shareWhatsApp=function(type,no){window.open('https://wa.me/?text='+encodeURIComponent('Dear Customer, please find your '+docTitle(type)+' '+no+' from K&M TechSpire Solution.'),'_blank');};
function showStatement(customerId){route('statements');}
function simpleModule(key){var label=(modules.find(function(m){return m[0]===key;})||['',key])[1];app.innerHTML=pageHead(label,'All buttons in this module are accessible.')+subnav(key)+'<div class="cards">'+(moduleSubs[key]||[]).map(function(s){return '<div class="module" data-sub="'+esc(s)+'" data-module="'+esc(key)+'"><h3>'+esc(s)+'</h3><span class="status green">Accessible</span><p class="muted">Click to open '+esc(s)+'.</p></div>';}).join('')+'</div>';}
['website','support','assets','vendors','employees','documents','reports','audit','settings'].forEach(function(k){pages[k]=function(){simpleModule(k);};});
pages.generic=function(k){simpleModule(k);};
renderNav();route('dashboard');
})();
